### ISSUE TITLE
Complex JSON nested objects and arrays

### ISSUE THREAD

**Issue by bvitos** [dataobservatory-eu/dataobservatory#1]
The July 7 state of the Green Deal SQLite database the codebook table contains incorrectly formatted JSON objects.
In complex JSON objects there should be no extra quotes (") before and after the object { } and array [ ] markers (so the object values should not be put in quotes), which also eliminates the need of escape characters.

So, for instance in Row 1:
{"RelatedItem":["SDMX Code List for Frequency"],"relatedItemType":["Dataset"],"relationType":["IsDocumentedBy"],"relatedItemIdentifier":["{\"id\":[\" CL_FREQ\"],\"dataset_code\":{},\"URI\":[\"https://sdmx.org/?page_id=3215/\"],\"DOI\":{},\"Version\":[\"2.1\"],\"idAtSource\":{},\"Other\":{}}"]}
Should be:
{"RelatedItem":["SDMX Code List for Frequency"],"relatedItemType":["Dataset"],"relationType":["IsDocumentedBy"],"relatedItemIdentifier":[{"id":[" CL_FREQ"],"dataset_code":{},"URI":["https://sdmx.org/?page_id=3215/"],"DOI":{},"Version":["2.1"],"idAtSource":{},"Other":{}}]}

Changes:
- "relatedItemIdentifier":["{  ->  "relatedItemIdentifier":[{
- "Other\":{}}"]}  ->  "Other":{}}]}
- Escape characters \ removed

The correct version can be conveniently proofed with a JSON parser such as http://json.parser.online.fr/

**Comment by antaldaniel** [comment]
I think that this is a more complex issues than malformatting. The current JSON, or JSON-like text converts into an R or Python list, or a data.frame in 1 or 2 steps.  It is a textual version of the list.  

I will first consult the Zenodo and DataCite API, becaue the main reason in the nested metadata is to allow programmatic connection to Zenodo and doi.org.

**Comment by antaldaniel** [comment]
@bvitos Can you handle JSON-LD type JSON? That is what most open Science or Stat API's use. https://json-ld.org/

**Comment by bvitos** [comment]
I'm not sure if we need Linked Data format at this stage. The APIs I checked are compliant with Datacite, which (according to https://support.datacite.org/docs/api) follows the JSON API specification:
https://jsonapi.org/
This format is displayed properly by Datasette.

Following the JSON API specification, the example above would be simply:
{"RelatedItem":"SDMX Code List for Frequency","relatedItemType":"Dataset","relationType":"IsDocumentedBy","relatedItemIdentifier":[{"id":"CL_FREQ","dataset_code":{},"URI":"https://sdmx.org/?page_id=3215/","DOI":{},"Version":"2.1","idAtSource":{},"Other":{}}]}

This Datacite-compliant format would be displayed on api.greendeal.dataobservatory.eu as:

{
    "RelatedItem":"SDMX Code List for Frequency",
    "relatedItemType":"Dataset",
    "relationType":"IsDocumentedBy",
    "relatedItemIdentifier":[
        {
            "id":"CL_FREQ",
            "dataset_code":{},
            "URI":"https://sdmx.org/?page_id=3215/",
            "DOI":{},
            "Version":"2.1",
            "idAtSource":{},
            "Other":{}
        }
    ]
}

So my suggestion would be to follow the formatting of the example laid out on https://jsonapi.org/ , which would be correctly parsed by Datasette, and it would be Datacite-compliant too.

**Comment by antaldaniel** [comment]
The problem is that we have to connect to other APIs, too, and they use JSON-LD. However, I think think that the only syntax difference is that there are some mandatory elements, which have a special (metadata) meaning and must always start with a  .  Would the special character @ cause any issue in the Datasette parser?

_No extra processors or software libraries are necessary to use JSON-LD in its most basic form. The language provides developers with a very easy learning curve. Developers not concerned with Linked Data only need to understand JSON, and know to include but ignore the @context property, to use the basic functionality in JSON-LD._

**Compatibility**
_A JSON-LD document is always a valid JSON document. This ensures that all of the standard JSON libraries work seamlessly with JSON-LD documents._

[Example](https://json-ld.org/):
{
  "@context": "https://json-ld.org/contexts/person.jsonld",
  "@id": "http://dbpedia.org/resource/John_Lennon",
  "name": "John Lennon",
  "born": "1940-10-09",
  "spouse": "http://dbpedia.org/resource/Cynthia_Lennon"
}

**Comment by bvitos** [comment]
Got it! Yes, the syntax extended with the @... keys is correctly parsed in Datasette. So we will be good with the basic JSON-LD format.
